source "http://rubygems.org"

# Uncomment the following lines if you are planing to
# use a local code of mailboxer or avatar_for_rails gems
#
# gem 'mailboxer', :path => '../mailboxer'
# gem 'avatars_for_rails', :path => '../avatars_for_rails'

# Temporary: we need to reference the latest thiking-sphinx from the rails3 branch
gem 'thinking-sphinx', :git=>'https://github.com/freelancing-god/thinking-sphinx.git', :branch => "rails3"

gemspec
